FROM bellsoft/liberica-openjdk-alpine-musl:11.0.14

ENV HOME=/home/modelfinder
WORKDIR $HOME
COPY modelfinder-server/target/modelfinder.jar modelfinder.jar
RUN chown 1001:0 $HOME && \
    chmod g+rw $HOME && \
    ls -la

USER 1001
EXPOSE 8080
ENV LOG4J_FORMAT_MSG_NO_LOOKUPS=true
CMD java -XX:MaxRAMPercentage=80.0 -jar modelfinder.jar
