FROM abiosoft/caddy:latest

LABEL name="sogis/modelfinder-proxy"
LABEL vendor="AGI"
LABEL url="https://agi.so.ch"
LABEL summary="Image based on abiosoft/caddy."
LABEL description="This image provides a proxy server for modelfinder services."

COPY Caddyfile /etc/Caddyfile
