# ========================
# TOMCAT
# ========================
server:
  tomcat:
    additional-tld-skip-patterns: '*.jar'
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024

# ========================
# SPRING
# ========================
logging:
  level:
    org.springframework: ${LOG_LEVEL:INFO}
    ch.so.agi: ${LOG_LEVEL_AGI:INFO} 

spring:
  web:
    resources:
        static-locations: classpath:/launcherDir/,classpath:/public/
    #resources:
     #   static-locations: classpath:/launcherDir/,classpath:/public/
    devtools:
        restart:
            additional-exclude: launcherDir/**

management:
    health:
        probes:
            enabled: true
    endpoint:
        health: 
            show-details: always

# spring:
#     profiles:
#         active: test 

# ========================
# APPLICATION
# ========================   
#lucene:
#    queryDefaultRecords: ${LUCENE_QUERY_DEFAULT_RECORDS:10}
#    queryMaxRecords: ${LUCENE_QUERY_MAX_RECORDS:50}

app:
    connectTimeout: ${connectTimeout:2000}
    readTimeout: ${readTimeout:8000}
    myVar: ${VAR:defaultValue}
    index-directory: ${indexDirectory:/tmp/}
    repositories:
      - http://models.interlis.ch
      #- http://models.geo.admin.ch
      #- https://geo.so.ch/models
      #- http://models.geo.gl.ch
