# ========================
# TOMCAT
# ========================
server:
  tomcat:
    additional-tld-skip-patterns: '*.jar'
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024

# ========================
# SPRING
# ========================
logging:
  level:
    org.springframework: INFO 

spring:
    resources:
        static-locations: classpath:/launcherDir/,classpath:/public/
    devtools:
        restart:
            additional-exclude: launcherDir/**

management:
  health:
    probes:
      enabled: true
  endpoint:
    health: 
      show-details: always


# spring:
#     profiles:
#         active: test 

# ========================
# APPLICATION
# ========================
app:
    myVar: ${VAR:defaultValue}
    index-directory: ${indexDirectory:/tmp/}
    repositories:
      - http://models.geo.admin.ch
      #- https://geo.so.ch/models
    default-repositories:
      - http://models.interlis.ch/ 
      - http://models.geo.kgk-cgc.ch/ 
      - http://models.geo.admin.ch/ 
