FROM quay.io/quarkus/quarkus-micro-image:1.0

ENV HOME=/work
WORKDIR $HOME

RUN chown 1001 /work \
    && chmod "g+rwX" /work \
    && chown 1001:root /work
COPY --chown=1001:root target/modelfinder-server /work/application

EXPOSE 8080
USER 1001

ENV LOG4J_FORMAT_MSG_NO_LOOKUPS=true
CMD ["./application"]
