FROM alpine:3.16

ARG UID=1001
RUN adduser -S modelfinder -u $UID

ENV HOME=/work
WORKDIR $HOME

COPY target/modelfinder-server ./application
RUN chown $UID:0 . && \
    chmod 0775 . && \
    ls -la

USER $UID
EXPOSE 8080
ENV LOG4J_FORMAT_MSG_NO_LOOKUPS=true
CMD ["./application"]