name: modelfinder

on: [push]

jobs:
  build:
    env:
      DOCKER_ACCOUNT: sogis
      DOCKER_REPO: modelfinder
      DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}} 
      DIGITALOCEAN_TOKEN: ${{secrets.DIGITALOCEAN_TOKEN}}
      BUILD_NUMBER: ${{ github.run_number }}
    runs-on: ubuntu-latest
    steps:
      - name: Print new build number
        run: echo "Build number is $BUILD_NUMBER"
      - uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Build Jar and create Docker Image
        run: |
          ./mvnw clean package -Penv-prod
          echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
          docker pull $DOCKER_ACCOUNT/$DOCKER_REPO:latest
          docker build -t $DOCKER_ACCOUNT/$DOCKER_REPO:latest -f Dockerfile.jvm .
      - name: Push Docker Images
        run: |
          echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
          docker images
          docker push $DOCKER_ACCOUNT/$DOCKER_REPO:latest
        if: ${{ github.ref == 'refs/heads/main' }}  
      - name: Deploy to Digital Ocean App Platform
        run: |
          curl -X POST -H "Content-Type: application/json" -H "Authorization: Bearer $DIGITALOCEAN_TOKEN" "https://api.digitalocean.com/v2/apps/a07f64e0-a50e-4466-a34b-63c6dc952d93/deployments"
        if: ${{ github.ref == 'refs/heads/main' }} 
